### ISSUE TITLE
Sim environment issue

### ISSUE THREAD

**Issue by zcase** [HimGautam/LearningToFly#1]
So I tried what have and noticed that the block just ends up falling on start. What version of of everything are you using?

**Comment by HimGautam** [comment]
Hi @zcase,
I am using the following versions:
1. Python 3.9.7
2. tensorflow 2.4.1
3. numpy 1.22.3
4. gym  0.21.0
5. gym-pybullet-drones 1.0.0
6. jupyter notebook   6.4.8
7. wandb  0.12.11 (optional for monitoring the training)

**Comment by zcase** [comment]
How did you get the block to stay in the air without the drone colliding into it? Looks like I'm using 1.0.0 of the environment as well but as soon as the simulation starts the block drops to the ground.

**Comment by HimGautam** [comment]
Hi,
I am using a custom urdf file of cube with zero inertia. I am updating my repository to with the files required. The files named "cube.obj" and  "cube_small.urdf" should be in the same directory with Base.py.
